#!/bin/csh -f

if ( "$#argv" < "1" ) then
  echo  usage: MakeDistribution number
  exit
endif

rm -rf gl2ps-$1/
mkdir gl2ps-$1

cd doc
latex gl2ps
latex gl2ps
dvips gl2ps -o
l2h gl2ps
rm -f gl2ps.toc gl2ps.out gl2ps.aux
pdflatex gl2ps
pdflatex gl2ps

cd ..
cp TODO COPYING.LIB gl2ps.c gl2ps.h\
   doc/gl2ps.ps doc/gl2ps.pdf gl2ps-$1/
chmod -R 755 gl2ps-$1
rm -f gl2ps-$1.tar* gm2ps.ps gl2ps.pdf gl2ps.html
tar cvf gl2ps-$1.tar gl2ps-$1
gzip gl2ps-$1.tar
touch gl2ps-$1.tar.gz
cd gl2ps-$1 && zip -r gl2ps-$1.zip *
mv gl2ps-$1.zip ..
cd ..
rm -rf gl2ps-$1
cp doc/gl2ps.ps doc/gl2ps.pdf doc/gl2ps.html .
