#! /bin/csh -f

if ( "$#argv" < "1" ) then
  echo  usage: MakeDistribution number
  exit
endif

rm -rf gl2ps-$1/
mkdir gl2ps-$1

cd doc
latex gl2ps
latex gl2ps
dvips gl2ps -o
l2h gl2ps
rm -f gl2ps.toc gl2ps.out
pdflatex gl2ps
pdflatex gl2ps

cd ..
cp TODO COPYING.LIB gl2ps.c gl2ps.h\
   doc/gl2ps.tex doc/gl2ps.html doc/gl2ps.ps doc/gl2ps.pdf gl2ps-$1/
chmod -R 755 gl2ps-$1
tar cvf gl2ps-$1.tar gl2ps-$1
gzip gl2ps-$1.tar
touch gl2ps-$1.tar.gz
